// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlk5y3CGJwX4clC13Y09yna9KTY1pFOF8',
    appId: '1:706260721856:web:4df1c215b8f4325213cd25',
    messagingSenderId: '706260721856',
    projectId: 'siri-4c010',
    authDomain: 'siri-4c010.firebaseapp.com',
    storageBucket: 'siri-4c010.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAT3PG637cD6_iwaGCCCctxzUvCmTWzC0Y',
    appId: '1:706260721856:android:2993a5bfbd73679413cd25',
    messagingSenderId: '706260721856',
    projectId: 'siri-4c010',
    storageBucket: 'siri-4c010.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXdSpY2YV8TVbw7x1hXdWI5XeuBm8VtXM',
    appId: '1:706260721856:ios:ed06d3f78845f11c13cd25',
    messagingSenderId: '706260721856',
    projectId: 'siri-4c010',
    storageBucket: 'siri-4c010.appspot.com',
    iosBundleId: 'com.example.siri',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXdSpY2YV8TVbw7x1hXdWI5XeuBm8VtXM',
    appId: '1:706260721856:ios:bf3443f54e1b765a13cd25',
    messagingSenderId: '706260721856',
    projectId: 'siri-4c010',
    storageBucket: 'siri-4c010.appspot.com',
    iosBundleId: 'com.example.siri.RunnerTests',
  );
}
